name: Build PR preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install and Build
        run: |
          pnpm install --ignore-scripts --fix-lockfile
          pnpm run build

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NB
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/

      - name: Save build directory
        run: |
          mkdir -p ./pr_site
          mv dist ./pr_site/.
      - uses: actions/upload-artifact@v2
        with:
          name: pr_site
          path: pr_site/
