name: CI deploy

on:
  push:
    branches:
      - main
jobs:
  deploy-production:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v3

      - name: Fix 404 on page reload 🚧
        uses: sliit-foss/actions/preview-deployments/404@main

      - name: Build 🏗️
        uses: ./.github/actions/build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist/
          branch: gh-pages
          clean-exclude: preview
